24 get profile
di-collective/akasia-mobile pull request #4
Opened 2024-05-31 07:14 UTC by hutomosaktikartiko

2024-05-31 09:22 UTC, bastianrob requested changes

2024-05-31 09:22 UTC, bastianrob commented on lib/features/account/data/datasources/remote/account_remote_datasource.dart
> +      Logger.info('getProfile accessToken: $accessToken');
Jangan di print Access tokennya

2024-06-03 02:10 UTC, hutomosaktikartiko commented on lib/features/account/data/datasources/remote/account_remote_datasource.dart
> +      Logger.info('getProfile accessToken: $accessToken');
log nya muncul di mode development aja mas

2024-06-03 02:18 UTC, rahmatsyalim approved these changes

2024-06-04 06:09 UTC, bastianrob approved these changes

2024-06-04 06:24 UTC, merged